#!/bin/sh
python update_repo.py ../skins-addons/resource.uisounds.iconmix ../skins-addons/script.iconmixtools ../skins-addons/skin.iconmix-jarvis ../skins-addons/skin.iconmix-krypton ../skins-addons/skin.iconmix-leia
git add .
git commit -a -m "mise a jour"
git push > lastgit.txt

read